config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  root to: 'movies#index'

  namespace :admin do
    resources :users
  end
  

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  
  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes,
        numericality: { only_integer: true }
  validates :description, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_future
  validate :one_form_of_image_required

  mount_uploader :poster_image_url, ImageUploader

  def review_average    
    if reviews && reviews.size > 0
      reviews.sum(:rating_out_of_ten)/reviews.size
    end
  end

  scope :by_title_or_director, -> (search) { where('title LIKE ? OR director LIKE ?', "%#{search}%", "%#{search}%") }
  scope :by_duration_short, -> { where("runtime_in_minutes < 90") }
  scope :by_duration_medium, -> { where("runtime_in_minutes BETWEEN 90 AND 120") }
  scope :by_duration_long, -> { where("runtime_in_minutes > 120") }


  # def self.by_title(title)
  #   where('title LIKE ?', "%#{title}%")
  # end

  def self.search(search, option)
    movies = Movie.all

    if !search.blank?
      search.split(' ').each do |query|
        movies = movies.by_title_or_director(query)
      end
    end
    case option.to_s.to_i

    when 1
      movies = movies.by_duration_short
    when 2
      movies = movies.by_duration_medium
    when 3
      movies = movies.by_duration_long
    end

    movies
  end


  protected 

  def one_form_of_image_required
    if !image_url.present? && !poster_image_url.present?
      errors.add(:image_url, "Please upload an image or give an image url")
    end
  end

  def release_date_is_in_the_future
    if release_date.present?
      errors.add(:release_date, "should be in the future") if release_date < Date.today
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
  belongs_to :movie, dependent: :destroy

  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true  
  validates :rating_out_of_ten, :inclusion => 1..10

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :reviews

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, length: { in: 6..20 }, on: :create

  def full_name
    "#{firstname} #{lastname}"
  end

    
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :restrict_admin

  def switch_to_user
    @current_user = User.find(params[:id])
    session[:user_id] = @current_user.id
  end

  def switch_to_admin
    
  end
 
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "#{@user.full_name} was created succesfully"
    else
      render :'admin/users/new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(user_params)
    if @user.save
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy    

    if @user.destroy
      # Tell the UserMailer to send delete email after destroy
      UserMailer.delete_confirmation(@user).deliver
      redirect_to admin_users_path, notice: "#{@user.full_name} was deleted succesfully"
      flash[:success] = 'Deleted successfully.'

    else
      render :new
    end

  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :admin, :password, :password_confirmation)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def restrict_admin
    if !current_user.admin
      redirect_to movies_path
    end
  end

 


  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  helper_method :switch

end 

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  
  def index
    @movies = Movie.all
    @movies = @movies.search(params[:search],params[:option])    
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update_attributes(movie_params)
    if @movie.save
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  protected

  def movie_params
    params.require(:movie).permit(:title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :image_url, :description)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :restrict_access
  before_filter :load_movie

  def new    
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected 

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end

  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new    
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def destroy
    @current_user = nil
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id # auto log in
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end



  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
    <%= link_to "Back to all users", admin_users_path, class: "btn btn-info" %>
    </div>
  </div>

  <h2 class="text-center">Edit User</h2>

  <div class="row">
    <div class="col-md-offset-4 col-md-4">

      <%= form_for [:admin, @user] do |f| %>
        <% if @user.errors.any? %>
          <div>
            <h4 class="text-center"><%= pluralize(@user.errors.count, "error") %> ocurred:</h4>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div>
          <%= f.label "email" %><br>
          <%= f.text_field "email", class: "form-control" %>
        </div>
        <div>
          <%= f.label "firstname", "First Name" %><br>
          <%= f.text_field "firstname", class: "form-control" %>
        </div>
        <div>
          <%= f.label "lastname", "Last Name" %><br>
          <%= f.text_field "lastname", class: "form-control" %>
        </div>
        <div>
          <%= f.label "password" %><br>
          <%= f.password_field "password", class: "form-control" %>
        </div>
        <div>
          <%= f.label "password_confirmation" %><br>
          <%= f.password_field "password_confirmation", class: "form-control" %>
        </div>
        <div>
          <%= f.label "admin" %><br>
          <%= f.check_box "admin" %>
        </div>
        <div><%= f.submit "Submit", class: "btn btn-submit btn-margin" %></div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2">
    <%= link_to "Create New User", new_admin_user_path, method: :get, class: "btn btn-info" %>
    </div>
  </div>

  <h2 class="text-center">Users</h2>
    <div class="row">
        <table class="table table-hover"> 
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Admin</th> 
            <th>Created</th> 
            <th>Updated</th>  
            <th>Delete/Edit</th>            
          </tr>
        </thead>
        <tbody>
          
          <% @users.each do |user| %>
            <tr>
              <th scope="row"><%= user.id %></th>
              <td><%= user.full_name %></td>
              <td><%= user.email %></td>
              <td><%= user.admin %></td>
              <td><%= user.created_at %></td>
              <td><%= user.updated_at %></td>
              <td style="display: -webkit-inline-box;">
              <%= link_to "edit", edit_admin_user_path(user.id), method: :get, class: "btn btn-submit", style: "margin-right: 4px;" %> 
              <%= link_to "delete", admin_user_path(user.id), method: :delete, confirm: "You sure?", class: "btn btn-delete" %>
              </td>
            </tr>  
          <% end %>          
        </tbody>
      </table>
    
  </div>
</div>

app/views/admin/users/new.html.erb
<h2 class="text-center">Sign a user up</h2>
<div class="container">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <%= form_for [:admin, @user] do |f| %>
        <% if @user.errors.any? %>
          <div>
            <h4 class="text-center"><%= pluralize(@user.errors.count, "error") %> ocurred:</h4>
            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div>
          <%= f.label "email" %>
          <%= f.text_field "email", class: "form-control" %>
        </div>
        <div>
          <%= f.label "firstname", "First Name" %>
          <%= f.text_field "firstname", class: "form-control" %>
        </div>
        <div>
          <%= f.label "lastname", "Last Name" %>
          <%= f.text_field "lastname", class: "form-control" %>
        </div>
        <div>
          <%= f.label "password" %>
          <%= f.password_field "password", class: "form-control" %>
        </div>
        <div>
          <%= f.label "password_confirmation" %>
          <%= f.password_field "password_confirmation", class: "form-control" %>
        </div>
        <div>
          <%= f.label "admin" %><%= f.check_box "admin" %>
        </div>
        <div><%= f.submit "Submit", class: "btn btn-submit btn-margin" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<%= link_to "Back to all users", admin_users_path %>


<h2><%= @user.full_name %> </h2>
<p>Created:<%= @user.created_at %> </p>
<p>Last Updated:<%= @user.updated_at %> </p>

<p>(<%= link_to "edit", edit_admin_user_path(@user) %>)</p>
<p>(<%= link_to "delete", admin_user_path, method: :delete, confirm: "You sure?" %>)</p>

app/views/layouts/_navbarbuttons.html.erb
<div class="navbar-form navbar-right">
  <% if current_user %>
   <%= link_to "Logout", session_path("current"), method: :delete, class: "btn btn-submit" %></button>
  <% else %>
    <%= link_to "Login", new_session_path, class: "btn btn-submit" %>
    <%= link_to "Sign Up", new_user_path, class: "btn btn-submit" %>
  <% end %>    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenBananas</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Bangers' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
</head>
<body>

  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">RottenBananas</a>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">      
          <% if current_user %>
            <li><%= link_to current_user.firstname, user_path(current_user) %></li>
            <li><%= link_to "Submit a movie!", new_movie_path %></li>
          <% end %>
          <% if current_user && current_user.admin %>                 
            <li><%= link_to "User Panel", admin_users_path %></li> 
          <% end %>      
        </ul>  
        <%= render 'layouts/navbarbuttons' %>      
      </div>
    </div>
  </nav>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value) %>
    <% end %>
<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for @movie do |f| %>
        <% if @movie.errors.any? %>
          <div>
            <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
            <ul>
              <% @movie.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div>
          <%= f.label "title" %>
          <%= f.text_field "title", class: 'form-control' %>
        </div>
        <div>
          <%= f.label "release_date" %>
          <%= f.date_field "release_date", class: 'form-control' %>
        </div>
        <div>
          <%= f.label "director" %>
          <%= f.text_field "director", class: 'form-control' %>
        </div>
        <div>
          <%= f.label "runtime_in_minutes" %>
          <%= f.text_field "runtime_in_minutes", class: 'form-control' %>
        </div>
        <div>
          <%= f.label "Upload Image" %>
          <%= f.file_field "poster_image_url", class: 'form-control' %>
        </div>
        <div>
          <%= f.label "Image Url" %>
          <%= f.text_field "image_url", class: 'form-control' %>
        </div>
        <div>
          <%= f.label "description" %>
          <%= f.text_area "description", class: 'form-control' %>
        </div>
        <div>
          <%= f.submit "Submit", class: 'btn btn-submit btn-margin' %> 
        </div>
      <% end %> 
    </div>
  </div>

app/views/movies/_movie.html.erb
<div class="row row-margin">
  <% @movies.each do |movie| %>
      <div class="movie_post_box col-xs-6 col-sm-4">
        <div class="image_center col-sm-12">
        <%= link_to image_tag(movie.image_url ? movie.image_url : movie.poster_image_url_url(:thumb), class: "poster-margin img-responsive center-block image-size"), movie_path(movie) %>
        </div>
        <div class="text-center">
          <h4><%= link_to movie.title, movie_path(movie), class: "movie-title" %></h4>
          <h5><%= formatted_date(movie.release_date) %></h5>
          <p> <%= movie.review_average %>/10</p>
          <h5>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h5>
          <p><%= movie.description %></p>
        </div>
      </div>
  <% end %>
</div>

app/views/movies/edit.html.erb
<div class="container">
  <div class="row">
    <%= link_to "Back to this movie", movie_path(@movie), class: "btn btn-info" %>
  </div>

  <h2 class="text-center">Edit this movie.</h2>
    <%= render 'form' %>
</div>

app/views/movies/index.html.erb
<h1 class="logo text-center">Rotten Bananas</h1>
<div class="container">
  <div class="row search_row">

        <div class="col-md-offset-2 col-md-4">
          <div class="col-md-2">
          <%= form_tag movies_path, :method => 'get' do %>        
          <label>Search</label>
          </div>
          <div class="col-md-10">
           <%= text_field_tag :search, params[:search], class: "form-control" %>
           </div>
        </div>
        <div class="col-md-4">
          <div class="col-md-2">
            <label>Duration</label>
          </div>
          <div class="col-md-8">
           <%= select_tag(:option, options_for_select([['Under 90 min', 1], ['Between 90 & 120 min', 2 ], ['Over 120 min', 3 ]]), :prompt => "Any Runtime", class: "form-control") %>
          </div>
          <div class="col-md-2">
            <%= submit_tag "Submit", :name => nil, class: "btn-submit btn" %>
          </div>
        </div>

        <% end %>
  </div>
      <%= render 'movie' %>
</div>

app/views/movies/new.html.erb
<div class="container">

  <h2 class="text-center">New Movie</h2>
    <%= render 'form' %>
</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="movie-profile row">
    <div class="col-md-offset-2 col-md-4">
      <div class="col-md-offset-2 col-md-8">
        <%= image_tag(@movie.image_url ? @movie.image_url : @movie.poster_image_url_url(:thumb), class: "image-size") %>
      </div>
    </div>
    <div class="col-md-4">
      <h2><%= @movie.title %></h2>
      <h4> <%= link_to "edit", edit_movie_path(@movie), class: "btn btn-info" %>  <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?", class: "btn btn-danger" %></h4>

      <h3><%= formatted_date(@movie.release_date) %></h3>
      <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
      <p><%= @movie.description %></p>
      <p><%= @movie.review_average %>/10</p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <h3>Reviews of <em><%= @movie.title %></em></h3>
      <% if current_user %>
        <% @movie.reviews.each do |review| %>
          <% if review.user %>
          <div class="text-center col-md-6">
            <div class="review-block col-md-offset-1 col-md-10">
              <p><%= review.text %></p>
              <p><%= review.rating_out_of_ten %>/10</p>
              <p><%= link_to review.user.full_name, user_path(review.user)  %></p>
            </div>
          </div>
          <% end %>
        <% end %>
        <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
      <% else %>
        <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
      <% end %>
    </div>
  </div>

</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">Write a review of <em><%= @movie.title %></em>.</h2>
    <div class="col-md-offset-4 col-md-4">     

      <%= form_for ([@movie, @review]) do |f| %>
        <% if @review.errors.any? %>
        <div>
          <h4><%= pluralize(@review.errors.count, "error") %>, prevented your review from being saved:</h4>
          <ul>
            <% @review.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>

        <div>
          <%= f.label "text" %>
          <%= f.text_area "text", class: "form-control" %>
        </div>
        <div>
          <%= f.label "rating_out_of_ten" %>
          <%= f.number_field "rating_out_of_ten", min: 1, max: 10 %>
        </div>
        <div><%= f.submit "Submit", class: "btn btn-submit btn-margin" %></div>

      <% end %>
    </div>
  </div>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h2 class="text-center">Sign Up</h2>
      <div class="col-md-offset-4 col-md-4">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div>
          <h4 class="text-center"><%= pluralize(@user.errors.count, "error") %> ocurred:</h4>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label "email" %>
        <%= f.text_field "email", class: "form-control" %>
      </div>
      <div>
        <%= f.label "firstname", "First Name" %>
        <%= f.text_field "firstname", class: "form-control" %>
      </div>
      <div>
        <%= f.label "lastname", "Last Name" %>
        <%= f.text_field "lastname", class: "form-control" %>
      </div>
      <div>
        <%= f.label "password" %>
        <%= f.password_field "password", class: "form-control" %>
      </div>
      <div>
        <%= f.label "password_confirmation" %>
        <%= f.password_field "password_confirmation", class: "form-control" %>
      </div>
      <div><%= f.submit "Submit", class: "btn-submit btn btn-margin" %></div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h4 class="text-center">Profile Page</h4>
  <div class="poster-margin row">
    <div class="col-md-offset-3 col-md-3">      
        <div class="profile-img"></div>      
    </div>
    <div class="text-center col-md-3">
      <h1><%= @user.full_name %></h1>
      <p><%= @user.email %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-offset-2 col-md-8">
      <% @user.reviews.each do |review| %>
      <div class="text-center col-md-offset-2 col-md-8">
        <h4><%= link_to review.text, movie_path(review.movie_id) %></h4>
        <p><%= review.rating_out_of_ten %>/10</p>
      </div>
      <% end %>
    </div>
  </div>

</div>